baseURL = 'https://ashehanSL.github.io/'
languageCode = 'en-us'
title = 'My Awesome Blog'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'My Awesome Blog'
    description = 'Welcome to my blog'
